### ISSUE TITLE
Firefox 40+: this.callbacks is undefined

### ISSUE THREAD

**Issue by fippo** [HenrikJoreteg/wildemitter#14]
i'm getting a
```
TypeError: this.callbacks is undefined
```
error in recent simplewebrtc builds when using firefox.

This seems to come from https://github.com/HenrikJoreteg/wildemitter/blob/master/wildemitter.js#L98
 but that looks ok?

Unfortunately, when trying to debug this, Firefox crashes.

**Comment by fippo** [comment]
@HenrikJoreteg @legastero?

**Comment by fippo** [comment]
ah... the constructor was called too late.

**Comment by tgabi333** [comment]
Could you please tell how does it happen?

**Comment by fippo** [comment]
@tgabi333 see https://github.com/HenrikJoreteg/SimpleWebRTC/commit/da54264b76b9cd59d48bdd3874b281ca2b47e77c -- in some cases the emtiter functionality was used before the constructor was called.

**Comment by tgabi333** [comment]
Thanks @fippo, but what cases exactly?
