### ISSUE TITLE
Request to add License

### ISSUE THREAD

**Issue by xdumaine** [HenrikJoreteg/wildemitter#21]
Hi, could you please add an appropriate license to this library? I'm hoping for MIT. Unfortunately this has been flagged by our company's legal compliance tools due to unknown license.

**Comment by HenrikJoreteg** [comment]
It has said "MIT" in the bot README for years: https://github.com/HenrikJoreteg/wildemitter#license

**Comment by xdumaine** [comment]
Ahh, thanks. Tooling looks for LICENSE or LICENSE.md files or license field in package.json. I'll add an exception.
